server:
  port: 8081

spring:
  application:
    name: patient-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      serviceServiceBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException


management:
  endpoints:
    web:
      exposure:
        include: health,info,resilience4j.circuitbreaker
  endpoint:
    health:
      show-details: always